### ISSUE TITLE
Scala Steward is not running

### ISSUE THREAD

**Issue by fthomas** [VirtusLab/scala-steward-repos#326]
https://github.com/pulls?q=author%3Ascala-steward+is%3Apr looks like Scala Steward hasn't been running since 2023-12-10.

**Comment by tgodzik** [comment]
Damn, I was only looking if the jobs run, but it seems something is off:
```
org.scalasteward.core.io.process$ProcessFailedException: '/opt/scala-steward/askpass.sh Password for 'https://scala-steward@api.github.com': ' exited with code 1.
cat: can't open '/mnt/secrets/personaltoken': No such file or directory
```
I need to check.

**Comment by tgodzik** [comment]
The only recent change I did was to change to:
`--forge-api-host \"https://api.github.com\" --forge-login \"scala-steward\"`
I can revert that, but any idea how this could break things?

**Comment by tgodzik** [comment]
I reverted the change, but would love to understand why that change broke things especially that it was only supposed to be a rename?

**Comment by fthomas** [comment]
I can't imagine how this change broke the askpass thing.

**Comment by tgodzik** [comment]
> I can't imagine how this change broke the askpass thing.

This might have been my bad when deploying then :/ I will take a look at it.

**Comment by fthomas** [comment]
Thanks for bringing it up again, @tgodzik!

> I will reintroduce the changes next week.

I'll delay merging https://github.com/scala-steward-org/scala-steward/pull/3241 until then.

**Comment by tgodzik** [comment]
I redeployed the version with `forge` change. I will get back to you tomorrow to see if it worked correctly.

**Comment by tgodzik** [comment]
Looks to be working alright, so it's a go. Sorry for the trouble, but Azure is not my cup of tea, had to bring in the heavy guns :sweat_smile:

**Comment by fthomas** [comment]
Thanks again, @tgodzik!
